github: Prajwal-Koirala
patreon:
open_collective: complexorganizations
ko_fi: prajwalkoirala23
tidelift:
community_bridge:
liberapay: prajwalkoirala23
issuehunt: complexorganizations
otechie:
custom: paypal.me/prajwalkoirala23
