blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/{user_name}/{repo_url}/issues
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/{user_name}/{repo_url}/issues
    about: Please report security vulnerabilities here.
