name: Lists are being updated.
on: [push]
#on:
#  schedule:
#    - cron: "0 */12 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go get -v
      - name: Build Test
        run: go build -v .
      - name: Run the build
        run: ./content-blocker -update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: main
          commit_options: "--no-verify --signoff"
          file_pattern: configs/*
          repository: .
          commit_user_name: Auto Update Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          status_options: "--untracked-files=no"
          add_options: "-u"
          push_options: "--force"
          skip_dirty_check: true
          skip_fetch: true
          disable_globbing: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_UPDATE_KEY }}
