name: Updating the resources
on: [push, pull_request]
#on:
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get .
      - name: Build Test
        run: go build .
      - name: Update the nameserver
        run: |
          sudo rm -f /etc/resolv.conf
          sudo echo "nameserver 8.8.8.8
          nameserver 8.8.4.4
          nameserver 2001:4860:4860::8888
          nameserver 2001:4860:4860::8844" >>/etc/resolv.conf
          cat /etc/resolv.conf
      - name: Generating new resources.
        run: ./content-blocker -update -logs
      - name: Update resources
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Updates are performed automatically. $(date)"
          git add .
          git push
