name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go get .
      - name: Run Test
        run: go run main.go -search="example.example"
      - name: Build Test
        run: go build .
      - name: Run the build
        run: ./content-blocker -search="example.example"
